name: Deployment Music Calculator (main)

on: 
  push:
    branches:
      - main

jobs: 
  deploy:
    name: Deployment Start
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Node 18.15.0
        uses: actions/setup-node@v3
        with: 
          node-version: 18.15.0
      - name: npm install and npm run build
        - run: npm i
        - run: npm run test
        - run: npm run build
      
      - name: copy files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "./dist/*"
          target: "./music-calculator/"
          strip_components: 1
